/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MenuPrincipalController;
import javax.swing.JOptionPane;

/**
 *
 * @author Positivo
 */
public class Menuprincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    /**
     * Creates new form Menuprincipal
     */
    public Menuprincipal() {
        initComponents();
        this.controller = new MenuPrincipalController(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucadastro = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        menuQuadra = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        AbaReserva = new javax.swing.JMenu();
        MenuReserva = new javax.swing.JMenuItem();
        AbaPagamento = new javax.swing.JMenu();
        MenuPagamento = new javax.swing.JMenuItem();
        AbaRelatorios = new javax.swing.JMenu();
        MenuRelatorios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 3, 36)); // NOI18N
        jLabel2.setText("Court Manager");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 280, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Menu principal.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, -1));

        jMenuBar1.setToolTipText("");

        menucadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/cliente-icon.png"))); // NOI18N
        menucadastro.setText("Cadastro");
        menucadastro.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        menucadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucadastroActionPerformed(evt);
            }
        });

        menuCliente.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menucadastro.add(menuCliente);

        menuQuadra.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        menuQuadra.setText("Quadra");
        menuQuadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuadraActionPerformed(evt);
            }
        });
        menucadastro.add(menuQuadra);

        menuUsuario.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        menuUsuario.setText("Usuário");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        menucadastro.add(menuUsuario);

        jMenuBar1.add(menucadastro);

        AbaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/agenda-icon.png"))); // NOI18N
        AbaReserva.setText("Reserva");
        AbaReserva.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        AbaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbaReservaActionPerformed(evt);
            }
        });

        MenuReserva.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        MenuReserva.setText("Reserva");
        MenuReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservaActionPerformed(evt);
            }
        });
        AbaReserva.add(MenuReserva);

        jMenuBar1.add(AbaReserva);

        AbaPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/iconPagamento.png"))); // NOI18N
        AbaPagamento.setText("Pagamento");
        AbaPagamento.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N

        MenuPagamento.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        MenuPagamento.setText("Pagamento");
        MenuPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPagamentoActionPerformed(evt);
            }
        });
        AbaPagamento.add(MenuPagamento);

        jMenuBar1.add(AbaPagamento);

        AbaRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/relatorioTrabalho-icon.png"))); // NOI18N
        AbaRelatorios.setText("Relatórios");
        AbaRelatorios.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N

        MenuRelatorios.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        MenuRelatorios.setText("Relatórios");
        MenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatoriosActionPerformed(evt);
            }
        });
        AbaRelatorios.add(MenuRelatorios);

        jMenuBar1.add(AbaRelatorios);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbaReservaActionPerformed
        // direcionar para a tela de reserva
        JOptionPane.showMessageDialog(rootPane, "Vou abrir o menu");
        this.controller.navegarParaAgenda();
    }//GEN-LAST:event_AbaReservaActionPerformed
        //VERIFICAR O FUNCIONAMENTO
    
    private void MenuReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservaActionPerformed
       JOptionPane.showMessageDialog(rootPane, "Vou abrir o menu");
        this.controller.navegarParaAgenda();
        
    }//GEN-LAST:event_MenuReservaActionPerformed

    private void MenuPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPagamentoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Vou abrir o menu");
        this.controller.navegarParaPagamento();// TODO add your handling code here:
    }//GEN-LAST:event_MenuPagamentoActionPerformed

    private void MenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatoriosActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Vou abrir menu");
        this.controller.navegarParaRelatorios();
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuRelatoriosActionPerformed

    
    private void menucadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menucadastroActionPerformed
    
    private void menuQuadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuadraActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Vou abrir menu");
        this.controller.navegarParaQuadra();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuQuadraActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Vou abrir menu");
        this.controller.navegarParaCliente();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Vou abrir menu");
        this.controller.navegarParaUsuario();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AbaPagamento;
    private javax.swing.JMenu AbaRelatorios;
    private javax.swing.JMenu AbaReserva;
    private javax.swing.JMenuItem MenuPagamento;
    private javax.swing.JMenuItem MenuRelatorios;
    private javax.swing.JMenuItem MenuReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuQuadra;
    private javax.swing.JMenuItem menuUsuario;
    private javax.swing.JMenu menucadastro;
    // End of variables declaration//GEN-END:variables
}
