/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Positivo
 */
public class Pagamento extends javax.swing.JFrame {

    /**
     * Creates new form Pagamento
     */
    public Pagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoFecharPagamento = new javax.swing.JButton();
        botaoCancelarPagamento = new javax.swing.JButton();
        botaoConfirmarPagamento = new javax.swing.JButton();
        DataPagamento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tipoPagamento = new javax.swing.JComboBox<>();
        pagamentoEfetuado = new javax.swing.JComboBox<>();
        valorTotalPagamento = new javax.swing.JTextField();
        duracaoPagamento = new javax.swing.JTextField();
        tipoQuadraPagamento = new javax.swing.JTextField();
        clientePagamento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        numeroQuadraPagamento = new javax.swing.JTextField();
        cpfclientePagamento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoFecharPagamento.setBackground(new java.awt.Color(255, 204, 0));
        botaoFecharPagamento.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        botaoFecharPagamento.setText("Fechar");
        getContentPane().add(botaoFecharPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 120, 30));

        botaoCancelarPagamento.setBackground(new java.awt.Color(204, 204, 204));
        botaoCancelarPagamento.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        botaoCancelarPagamento.setForeground(new java.awt.Color(255, 0, 51));
        botaoCancelarPagamento.setText("Cancelar");
        getContentPane().add(botaoCancelarPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 120, 30));

        botaoConfirmarPagamento.setBackground(new java.awt.Color(204, 255, 0));
        botaoConfirmarPagamento.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        botaoConfirmarPagamento.setForeground(new java.awt.Color(0, 153, 0));
        botaoConfirmarPagamento.setText("Confirmar");
        getContentPane().add(botaoConfirmarPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 120, 30));

        DataPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(DataPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 90, -1));

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Data Criação");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 100, -1));

        tipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crédito", "Débito", "Dinheiro", "Pix" }));
        getContentPane().add(tipoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 100, -1));

        pagamentoEfetuado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        getContentPane().add(pagamentoEfetuado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 100, -1));

        valorTotalPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTotalPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(valorTotalPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 70, -1));

        duracaoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracaoPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(duracaoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 70, -1));

        tipoQuadraPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoQuadraPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(tipoQuadraPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, -1));

        clientePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientePagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(clientePagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 340, -1));

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cliente");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, -1));

        numeroQuadraPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroQuadraPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(numeroQuadraPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        cpfclientePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfclientePagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(cpfclientePagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, -1));

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo Pagamento");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 120, 20));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pagto efetuado");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 110, 20));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valor Total");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 90, 20));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Duração");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 90, 20));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo Quadra");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 90, 20));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nº Quadra");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 80, 20));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF Cliente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Pagamento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 790, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/agenda-tela.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfclientePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfclientePagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfclientePagamentoActionPerformed

    private void numeroQuadraPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroQuadraPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroQuadraPagamentoActionPerformed

    private void clientePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientePagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientePagamentoActionPerformed

    private void tipoQuadraPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoQuadraPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoQuadraPagamentoActionPerformed

    private void duracaoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracaoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracaoPagamentoActionPerformed

    private void valorTotalPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTotalPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTotalPagamentoActionPerformed

    private void DataPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DataPagamento;
    private javax.swing.JButton botaoCancelarPagamento;
    private javax.swing.JButton botaoConfirmarPagamento;
    private javax.swing.JButton botaoFecharPagamento;
    private javax.swing.JTextField clientePagamento;
    private javax.swing.JTextField cpfclientePagamento;
    private javax.swing.JTextField duracaoPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numeroQuadraPagamento;
    private javax.swing.JComboBox<String> pagamentoEfetuado;
    private javax.swing.JComboBox<String> tipoPagamento;
    private javax.swing.JTextField tipoQuadraPagamento;
    private javax.swing.JTextField valorTotalPagamento;
    // End of variables declaration//GEN-END:variables
}
