/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Positivo
 */
public class Quadras extends javax.swing.JFrame {

    /**
     * Creates new form Quadras
     */
    public Quadras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoFecharQuadra = new javax.swing.JButton();
        botaoAlterarQuadra = new javax.swing.JButton();
        botaoExcluirQuadra = new javax.swing.JButton();
        botaoAdicionarQuadra = new javax.swing.JButton();
        dataCriacaoQuadra = new javax.swing.JTextField();
        cadastroValorQuadra = new javax.swing.JTextField();
        temBanco = new javax.swing.JComboBox<>();
        temArquibancada = new javax.swing.JComboBox<>();
        temCobertura = new javax.swing.JComboBox<>();
        tipoQuadra = new javax.swing.JComboBox<>();
        TextNumeroQuadra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoFecharQuadra.setBackground(new java.awt.Color(255, 204, 51));
        botaoFecharQuadra.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        botaoFecharQuadra.setText("Fechar");
        getContentPane().add(botaoFecharQuadra, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 110, 30));

        botaoAlterarQuadra.setBackground(new java.awt.Color(204, 204, 204));
        botaoAlterarQuadra.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        botaoAlterarQuadra.setForeground(new java.awt.Color(255, 153, 0));
        botaoAlterarQuadra.setText("Alterar");
        getContentPane().add(botaoAlterarQuadra, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 110, 30));

        botaoExcluirQuadra.setBackground(new java.awt.Color(204, 204, 255));
        botaoExcluirQuadra.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        botaoExcluirQuadra.setForeground(new java.awt.Color(255, 0, 0));
        botaoExcluirQuadra.setText("Excluir");
        botaoExcluirQuadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirQuadraActionPerformed(evt);
            }
        });
        getContentPane().add(botaoExcluirQuadra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 110, 30));

        botaoAdicionarQuadra.setBackground(new java.awt.Color(102, 255, 51));
        botaoAdicionarQuadra.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        botaoAdicionarQuadra.setForeground(new java.awt.Color(0, 153, 0));
        botaoAdicionarQuadra.setText("Adicionar");
        getContentPane().add(botaoAdicionarQuadra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 110, 30));

        dataCriacaoQuadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCriacaoQuadraActionPerformed(evt);
            }
        });
        getContentPane().add(dataCriacaoQuadra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 90, -1));

        cadastroValorQuadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroValorQuadraActionPerformed(evt);
            }
        });
        getContentPane().add(cadastroValorQuadra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 90, -1));

        temBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        getContentPane().add(temBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 90, -1));

        temArquibancada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        getContentPane().add(temArquibancada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 90, -1));

        temCobertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        getContentPane().add(temCobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 90, -1));

        tipoQuadra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saibro", "Rápida", "Beach Tênis" }));
        getContentPane().add(tipoQuadra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 90, -1));

        TextNumeroQuadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNumeroQuadraActionPerformed(evt);
            }
        });
        getContentPane().add(TextNumeroQuadra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 90, -1));

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dt. Criação");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Valor/ Hora");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Banco jogador");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Arquibancada");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Coberta");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nº Quadra");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Cadastro Quadra");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 790, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/agenda-tela.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNumeroQuadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNumeroQuadraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumeroQuadraActionPerformed

    private void cadastroValorQuadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroValorQuadraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroValorQuadraActionPerformed

    private void dataCriacaoQuadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCriacaoQuadraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCriacaoQuadraActionPerformed

    private void botaoExcluirQuadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirQuadraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirQuadraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quadras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quadras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quadras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quadras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quadras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextNumeroQuadra;
    private javax.swing.JButton botaoAdicionarQuadra;
    private javax.swing.JButton botaoAlterarQuadra;
    private javax.swing.JButton botaoExcluirQuadra;
    private javax.swing.JButton botaoFecharQuadra;
    private javax.swing.JTextField cadastroValorQuadra;
    private javax.swing.JTextField dataCriacaoQuadra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> temArquibancada;
    private javax.swing.JComboBox<String> temBanco;
    private javax.swing.JComboBox<String> temCobertura;
    private javax.swing.JComboBox<String> tipoQuadra;
    // End of variables declaration//GEN-END:variables
}
